### ISSUE TITLE
router.route("/test").get(...)

### ISSUE THREAD

**Issue by cypherix93** [spatools/express-async-router#2]
I am trying to use this router in the following pattern:

```
router.route("/test")
    .get(function(req, res)
    {
        // returned Promise rejects
    })
```

But `next()` is not getting called with the rejected Error.

It works if I use it like this:

```
router
    .get("/test", function(req, res)
    {
        // returned Promise rejects
    })
```

Would very much like the `router.route(...)` pattern supported. Appreciate any help.

**Comment by SomaticIT** [comment]
I can't reproduce your error, can you detail your issue ?
What are you doing inside the function before returning rejected Promise ?
What Promise library are you using ?
