### ISSUE TITLE
Subrouters don't working as async

### ISSUE THREAD

**Issue by isuvorov** [spatools/express-async-router#3]
Working good: 
```
  router.all('/some/thing',  async () => {
    console.log(111);
    await getPromise()
    console.log(222);
  },  async () => {
    console.log(333);
    const json = await getPromise()
    console.log(444);
    return json
  })
```
111, 222, 333, 444, return json

Working bad: 
```
  router2.all('/thing',  async () => {
    console.log(111);
    await getPromise()
    console.log(222);
  },  async () => {
    console.log(333);
    const json = await getPromise()
    console.log(444);
    return json
  })

router1.use('/some', router2)
```
111, 333, return null

**Comment by isuvorov** [comment]
asyncRouter.use(expressNativeRouter) ok
expressNativeRouter.use(asyncRouter) ok
asyncRouter.use(asyncRouter) not ok

I fixed it here https://github.com/isuvorov/express-async-router

**Comment by SomaticIT** [comment]
Thanks @isuvorov  for your work.
It's a good fix. I will review and merge it quickly.

I will notice you when I publish the fix in NPM.
