### ISSUE TITLE
Allow to pass array of RequestHandlers

### ISSUE THREAD

**Issue by fnky** [spatools/express-async-router#6]
As outlined in [Express docs for `app.METHOD`](https://expressjs.com/en/api.html#app.METHOD) the `callback` argument can be of these types:

- A middleware function.
- A series of middleware functions.
- An array of middleware functions.
- A combination of all the above.

So you can pass middleware like this:

```
app.get('/', middleware1, [middleware2, middleware3])
app.use(middleware1, [middleware2, middleware3], middleware4)
```

**Comment by SomaticIT** [comment]
Hello,
Sorry for my lack of time.
I published a new release `v0.1.14` which fix this issue. You can now pass array of middleware and the will be wrapped by `express-async-router`.
Thank you for your request.
